### ISSUE TITLE
unsupported operand type for /: 'str' and 'int'

### ISSUE THREAD

**Issue by cgosorio** [JoseBarbero/UBUMLaaS#254]
After the steps shown in the following sequence of screenshots, the application launch the error 
```
unsupported operand type for /: 'str' and 'int'
```
![Step-one](https://user-images.githubusercontent.com/7659408/110661618-0ce7f280-81c5-11eb-8a1c-1b182728f729.png)

![Step-two](https://user-images.githubusercontent.com/7659408/110661646-140f0080-81c5-11eb-8f13-bdce46fa059d.png)

![Step-three](https://user-images.githubusercontent.com/7659408/110661671-1a04e180-81c5-11eb-8a66-41a197608401.png)

![Step-four](https://user-images.githubusercontent.com/7659408/110661710-1f622c00-81c5-11eb-9df8-767758c8fa6c.png)

**Comment by jlgarridol** [comment]
The problem is that a classification dataset is being used on a regression problem. Since different libraries are used to run the algorithms and each method has its own error checking we leave the message as returned by the training algorithm.

In future versions the error output will be improved.
